"""Added relationships and seeded data

Revision ID: 08797991d449
Revises: 71cfc0086ec1
Create Date: 2023-09-03 16:21:45.818386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08797991d449'
down_revision = '71cfc0086ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
