"""Added Aggregate and Relationship Methods

Revision ID: 7a6454198df5
Revises: bf40b965a0a5
Create Date: 2023-09-03 17:35:40.663277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6454198df5'
down_revision = 'bf40b965a0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
