"""Added object relationship methods

Revision ID: bf40b965a0a5
Revises: 08797991d449
Create Date: 2023-09-03 17:00:46.013633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf40b965a0a5'
down_revision = '08797991d449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
